services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app  
    environment:
      DISCORD_TOKEN: "input your token"
    command: "cd /app && python3 bot.py"